require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios,  '16.4'
prepare_react_native_project!

use_modular_headers!

# to connect to firebase 
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

target 'SociApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
